-- Compativel com Postgres 16 (runtime) e H2 2.x (testes), de proposito:
-- mesmo schema.sql roda nos dois, sem perfil condicional.

-- memoria do que ja foi visto — sustenta a IDEMPOTENCIA
CREATE TABLE IF NOT EXISTS evento_processado (
    evento_id VARCHAR(64) PRIMARY KEY
);

-- o efeito de negocio — historico de peso por animal.
-- E TABELA DE ANEXAR (append-only), nao de sobrescrever: a curva de ganho de
-- peso so existe se cada leitura ficar guardada, nao so a mais recente. E
-- exatamente o "algo que vale reprocessar" do ADR-002.
CREATE TABLE IF NOT EXISTS historico_pesagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id VARCHAR(64) NOT NULL,
    peso_kg DOUBLE PRECISION NOT NULL,
    registrado_em TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_historico_pesagem_animal
    ON historico_pesagem (animal_id, registrado_em);
