-- Compativel com Postgres 16 (runtime) e H2 2.x (testes), de proposito:
-- mesmo schema.sql roda nos dois, sem perfil condicional.

-- Tabela de fazendas
CREATE TABLE IF NOT EXISTS fazenda (
    id VARCHAR(64) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- Tabela de lotes — cada lote pertence a uma fazenda
CREATE TABLE IF NOT EXISTS lote (
    id VARCHAR(64) PRIMARY KEY,
    numeracao INTEGER NOT NULL,
    fazenda_id VARCHAR(64) NOT NULL REFERENCES fazenda(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- Tabela de animais — cada animal pertence a um lote
CREATE TABLE IF NOT EXISTS animal (
    id VARCHAR(64) PRIMARY KEY,
    nome_do_animal VARCHAR(255) NOT NULL,
    raca VARCHAR(255) NOT NULL,
    idade INTEGER NOT NULL CHECK (idade >= 0),
    data_de_nascimento TIMESTAMP NOT NULL,
    lote_id VARCHAR(64) NOT NULL REFERENCES lote(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- memoria do que ja foi visto — sustenta a IDEMPOTENCIA
CREATE TABLE IF NOT EXISTS evento_processado (
    evento_id VARCHAR(64) PRIMARY KEY
);

-- o efeito de negocio — historico de peso por animal.
-- E TABELA DE ANEXAR (append-only), nao de sobrescrever: a curva de ganho de
-- peso so existe se cada leitura ficar guardada, nao so a mais recente. E
-- exatamente o "algo que vale reprocessar" do ADR-002.
CREATE TABLE IF NOT EXISTS historico_pesagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id VARCHAR(64) NOT NULL,
    peso_kg DOUBLE PRECISION NOT NULL,
    registrado_em TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_historico_pesagem_animal
    ON historico_pesagem (animal_id, registrado_em);

-- Historico append-only das vacinacoes consumidas pelo servico.
CREATE TABLE IF NOT EXISTS historico_vacinacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id VARCHAR(64) NOT NULL,
    vacina VARCHAR(255) NOT NULL,
    metodo_de_vacinacao VARCHAR(255) NOT NULL,
    registrado_em TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_historico_vacinacao_animal
    ON historico_vacinacao (animal_id, registrado_em);

-- Tabela de vendas — o ciclo comercial do animal (ADR-002).
-- Uma venda referencia UM animal OU UM lote (nunca os dois, nunca nenhum).
-- O peso_minimo_kg e a meta de peso acordada em contrato com o frigorifico.
CREATE TABLE IF NOT EXISTS venda (
    id VARCHAR(64) PRIMARY KEY,
    animal_id VARCHAR(64) REFERENCES animal(id),
    lote_id VARCHAR(64) REFERENCES lote(id),
    frigorifico VARCHAR(255) NOT NULL,
    peso_minimo_kg DOUBLE PRECISION NOT NULL CHECK (peso_minimo_kg > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    -- exatamente um alvo: animal XOR lote
    CHECK ( (animal_id IS NOT NULL AND lote_id IS NULL)
         OR (animal_id IS NULL AND lote_id IS NOT NULL) )
);

CREATE INDEX IF NOT EXISTS idx_venda_animal ON venda(animal_id);
CREATE INDEX IF NOT EXISTS idx_venda_lote ON venda(lote_id);

CREATE INDEX IF NOT EXISTS idx_lote_fazenda ON lote(fazenda_id);
CREATE INDEX IF NOT EXISTS idx_animal_lote ON animal(lote_id);

-- Estado vigente da dieta do animal — nao e' historico (nao ha' tabela
-- append-only para isso). E' escrita pela compensacao de
-- AnimalRejeitadoNoEmbarque (ADR-002): fica nula para todo animal que
-- nunca passou por essa reavaliacao.
ALTER TABLE animal ADD COLUMN IF NOT EXISTS dieta_atual VARCHAR(64);

-- Event store do agregado Lote (localizacao de pasto) — ADR-005.
-- Append-only: nenhuma linha e' alterada nem apagada depois de gravada.
-- (lote_id, versao) e' a chave: a propria restricao de unicidade e' o
-- mecanismo de deteccao de concorrencia — duas escritas tentando gravar a
-- mesma versao do mesmo lote colidem, so uma vence.
CREATE TABLE IF NOT EXISTS lote_evento_store (
    lote_id VARCHAR(64) NOT NULL,
    versao INTEGER NOT NULL,
    evento_id VARCHAR(64) NOT NULL,
    tipo_evento VARCHAR(64) NOT NULL,
    ocorrido_em TIMESTAMP NOT NULL,
    payload VARCHAR(4000) NOT NULL,
    PRIMARY KEY (lote_id, versao),
    UNIQUE (evento_id)
);

-- Projecao descartavel: onde cada lote esta agora, segundo o event store.
-- Nunca e' escrita por UPDATE de negocio direto — so pelo fold dos eventos
-- (LoteLocalizacaoService), seja incrementalmente ou por replay completo.
-- A fonte da verdade e' sempre o lote_evento_store; esta tabela pode ser
-- apagada e reconstruida inteira sem perder informacao.
CREATE TABLE IF NOT EXISTS lote_localizacao_atual (
    lote_id VARCHAR(64) PRIMARY KEY,
    pasto_atual_id VARCHAR(64),
    versao_da_projecao INTEGER NOT NULL,
    atualizado_em TIMESTAMP NOT NULL
);
