-- Compativel com Postgres 16 (runtime) e H2 2.x (testes), de proposito:
-- mesmo schema.sql roda nos dois, sem perfil condicional.

-- Tabela de fazendas
CREATE TABLE IF NOT EXISTS fazenda (
    id VARCHAR(64) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- Tabela de lotes — cada lote pertence a uma fazenda
CREATE TABLE IF NOT EXISTS lote (
    id VARCHAR(64) PRIMARY KEY,
    numeracao INTEGER NOT NULL,
    fazenda_id VARCHAR(64) NOT NULL REFERENCES fazenda(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- Tabela de animais — cada animal pertence a um lote
CREATE TABLE IF NOT EXISTS animal (
    id VARCHAR(64) PRIMARY KEY,
    nome_do_animal VARCHAR(255) NOT NULL,
    raca VARCHAR(255) NOT NULL,
    idade INTEGER NOT NULL CHECK (idade >= 0),
    data_de_nascimento TIMESTAMP NOT NULL,
    lote_id VARCHAR(64) NOT NULL REFERENCES lote(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- memoria do que ja foi visto — sustenta a IDEMPOTENCIA
CREATE TABLE IF NOT EXISTS evento_processado (
    evento_id VARCHAR(64) PRIMARY KEY
);

-- o efeito de negocio — historico de peso por animal.
-- E TABELA DE ANEXAR (append-only), nao de sobrescrever: a curva de ganho de
-- peso so existe se cada leitura ficar guardada, nao so a mais recente. E
-- exatamente o "algo que vale reprocessar" do ADR-002.
CREATE TABLE IF NOT EXISTS historico_pesagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id VARCHAR(64) NOT NULL,
    peso_kg DOUBLE PRECISION NOT NULL,
    registrado_em TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_historico_pesagem_animal
    ON historico_pesagem (animal_id, registrado_em);

-- Historico append-only das vacinacoes consumidas pelo servico.
CREATE TABLE IF NOT EXISTS historico_vacinacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id VARCHAR(64) NOT NULL,
    vacina VARCHAR(255) NOT NULL,
    metodo_de_vacinacao VARCHAR(255) NOT NULL,
    registrado_em TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_historico_vacinacao_animal
    ON historico_vacinacao (animal_id, registrado_em);

CREATE INDEX IF NOT EXISTS idx_lote_fazenda ON lote(fazenda_id);
CREATE INDEX IF NOT EXISTS idx_animal_lote ON animal(lote_id);
